### ISSUE TITLE
Remove "offline hours" from government salary

### ISSUE THREAD

**Issue by Azzurite** [D3nnis3n/White-Tiger-Feedback#22]
I don't really see a reason to pay government officials when they're not even in the game. This is not a full-time job like in the real world, you don't really have any "living" expenses. 

Also, even while in game, government officials still are allowed to and do things that are not government-related, So I would argue that the salary they still get during that is basically their "offline" pay.

**Comment by D3nnis3n** [comment]
Hello Azzurite,
thanks for your feedback. We have decided for this system for several reasons and after a short review decided to not change this behaviour.

There is several reasons for why we are doing this:
1. Many of the government jobs entail work that does not happen in the game, to differing degrees. The judges do not need to do anything ingame at all, but need to deal with partly hour-long cases on Discord; Senators work ingame is limited to law crafting, votes and their local government work (which they are NOT paid for federally, but supposed to be paid by the State), but they also mostly do their debates on the Discord when not in game. A online pay would not resemble their efforts. This is also true for all other government officials in lesser degree.
2. The payment based on online time would additionally be unfair, as it benefits those players that can play or idle a lot and hence violate the equity requirements of the constitution. Being online, as shown in 1. does not show how much work people actually did in relation to their office. A Senator that plays 12 hours a day will get paid 12 times as much as a Senator that is online only one hour a day, while both may have worked exactly the same on their Senator job - one hour.
3. Having all government officials being paid a flat salary is hence the most fair solution and also allows the government to calculate the expenses, as it at any time knows how many people receive salaries and how much.
4. We have introduced salaries as a mandatory government expense because we think it's the governments duty to compensate players working for it, having responsibilitites that go beyond those of normal players as a very basic foundation of a government, requiring the government to acquire funding. Not paying people for their work would neither be any realistic, any rewarding to actually take such a job nor be fair.
