### ISSUE TITLE
Give Advanced Masonry a modern upgrade

### ISSUE THREAD

**Issue by EddEco** [D3nnis3n/White-Tiger-Feedback#5]
Basically, Advanced masonry could do with some love, and to be honest, modern upgrade level 1's are wasted on Advanced Smelting, but equally you could remove MU's from either Industry or electronics and they would still be great skills.

Personally I think Advanced masonry would do well with taking MU4 from Electronics, as a lot of electronics components fit into Industry already.

This would definitely help masons late game and could see an increase in ashlar.

**Comment by D3nnis3n** [comment]
Check for which one to remove, RE MU1 getting benefit of AU.

Also, think of a narrative on what Advanced Masonry could actually produce that is a modern upgrade.

**Comment by weylint** [comment]
Adv. Masonry itself currently uses steel, cement and "rocks", so it's basically at the same technological level as Reinforced Concrete, Tier 3. Arguably lower, because it "only" uses steel, not a refined steel product like rebar. So if MU1 became Advanced Masonry, it might need an earlier place in the research chain. 

In reality, Ashlar itself is old enough. Depending on the size of its blocks it dates back to ancient greece. Also Machu Picchu comes to mind.
https://en.wikipedia.org/wiki/Ashlar

I would have guessed there'd be Ashlar/Advanced Masonry in the Meteor Race somewhere, esp. since in the past there wasn't a Modern Upgrade made by it.
Also: No Research depends on it atm.

**Comment by DanielKispert** [comment]
vote4close, was done
