### ISSUE TITLE
Lower the impact of food bonuses

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#51]
With our food SP scaling, we want to make sure that people need to eat T4 food to do T4 jobs, T3 food for T3 jobs and so on.
There are some problems with it though:
- if you minmax a lower tier food it is possible to reach the bracket one level higher
- if we would fix this by increasing the brackets, you also need to minmax your high tier food to reach its assigned bracket
- but the bracket of the high tier food should be reachable by just eating it and having it roughly balanced
- you need to keep your bonuses up right now to reach the limits if you start with an empty stomach

![grafik](https://user-images.githubusercontent.com/34270661/143784011-8a3414a5-e77e-43ea-bb71-f9a1dfe92498.png)
in this example, I ate a few pieces of T4 food and have a reasonably balanced stomach. I did not eat anything else in the 24h before.
The limit for T4 work is 115 SP right now. That means: 
1. I still cannot do T4 work even though I eat T4 food and balanced it a bit
2. someone that minmaxed T3 food through extreme bonuses could do it

Therefore I propose to:
1. reduce the SP levels to something you can reach with reasonable balancing on an empty stomach
2. reduce the effect that the various bonuses give you so you can not meet the now-lower SP level of the next tier with lower tier food (can not = can not as much as now, if extreme minmaxing makes it possible that's an edge case)

this would make it a lot easier for less playing people and newer people to take high skill jobs while still making them consume the highest tier food, like everyone else. The more skilled players can still minmax to maybe get a higher tier with lower tier food (and get more SP in general) but the difference between low skill and high skill would be less. Right now, the difference between "reasonable eating on an empty stomach" and "full minmax" is between 90 SP and 170 SP for T4 food, which is a lot

**Comment by stucko** [comment]
How about instead of that ,make the food requirement for job based on subtotal (raw nutrients, excluding bonuses)

that way T4 food will be required for T4 jobs (even minmaxing with T3 food cant bypass the requirement)

Balance, Variety, Craving bonuses then would be same as housing for 
1) accelerating skill progression
2) accelerating star acquisition

**Comment by D3nnis3n** [comment]
> How about instead of that ,make the food requirement for job based on subtotal (raw nutrients, excluding bonuses)
> 
> that way T4 food will be required for T4 jobs (even minmaxing with T3 food cant bypass the requirement)
> 
> Balance, Variety, Craving bonuses then would be same as housing for
> 
> 1. accelerating skill progression
> 2. accelerating star acquisition

Not sure if we can read that data, but I'd be for this.
Changing stuff at a still not finally released feature we're supposed to be testing (cravings, variety) is not something I would want before the feature is even released. We can consider that once it's been enabled by default, polished and around for a while, otherwise WT feedback becomes useless on that part in development.

**Comment by weylint** [comment]
Most problems seem to arise from balancing two ideas:

a) Cleverness. Giving bonusses to people for "cleverly" minmaxing their Food Bonus
b) SP Minimum. Eat T4 for T4 Crafts.

"Clever" T3 is more than equal to "random" T4. This may be intentional.

Solutions:
I) Remove either a) or b) both solve the issue.
II) Increase the difference between "random" T4 and "clever" T3, by 
- for example removing cravings *or* 
- removing Variety Bonus *or*
- increase the distance between Food-Tiers

**Comment by D3nnis3n** [comment]
Yeh, tinkering with cravings or variety bonus at this point is unfortunately not an option I'd approve, due to the reasons I've noted above. WT has an obligation to be useful for testing the actual game as well that takes precedence over a optimal adjustment just for the specific server, at least so long as actual testing is required. Cravings and Variety bonus are still beta features in need of testing and adjustments on a game level and hence are not ready for adaptions yet.

**Comment by DanielKispert** [comment]
if we can target the base food SP ("subtotal") with our food SP rule then that will also be sufficient to meet our goals of having the advanced food consumed and allowing everyone access to those skills without having to minmax

**Comment by DanielKispert** [comment]
base SP was added, closing
