### ISSUE TITLE
Forbid taxes that are sensitive to timing

### ISSUE THREAD

**Issue by thomasfn** [D3nnis3n/White-Tiger-Feedback#8]
e.g. income tax in the form we've seen the previous few iterations, as they are not equitable and strongly discriminate players based on timezone. With such taxes, players who aren't able to be online at or near the tax tick are at severe disadvantage, whereas players who are have a massive advantage as they are able to take actions to avoid the tax when the person who's offline obviously can't.

For example, consider the following hypothetical situation:
- sales tax of 10% for seller of any trade
- income tax that acts every 24hr at 3am, taxing 20% of any measured increase of wealth
- player A and player B who are both smelters and have similar levels of game knowledge, progression, daily playtime and are generally on a level playing field

1. at 8 PM, both player A and player B have 1000 Iron Bars stocked in their shops, for sale at a price of $5 ea, and have a balance of $0 each (after having spent all their money on buying Iron Concentrate)
2. both players log off, planning to spend all of their earnings in the morning on more Iron Concentrate for their business
3. at midnight, Engineering Corp Alpha comes and buys all 2000 Iron Bars from both players. Player A and Player B now have a wealth of $4500 each ($5000 - 10% sales tax)
4. at 2:30am, player B logs in as they are in a different timezone and for them it's not bed time yet. they see the $4500 in their account and go to spend it all on Iron Concentrate as planned, buying 450 for $10 each, then log out
5. at 3am the income tax ticks. Player A has a wealth increase of $4500 and is taxed 20% of that, so $900. Player B has a wealth increase of $0 and is taxed nothing.
5. at 6am, player A wakes up and logs in just before work, and goes to spend their $3600 on Iron Concentrate as planned, buying 360 for $10 each

Both players performed exactly the same activities and transactions, and play for exactly the same amount of time over the 10 hour period. However, player B now has a massive advantage since _they were only taxed $500 in total_ whereas player A has a severe disadvantage because _they were taxed $1400 in total_. The only reason for this huge difference in tax amount is when they were able to login. This is the very definition of inequitable and should strictly be unconstitutional.

Wealth tax suffers from similar issues. It should be mandatory for both taxes to be implemented in a way that is not sensitive to timing.

Note that the above "hypothetical" situation isn't actually theoretical, it happens on a daily basis on WT and people regularly complain about it. Unfortunately they just get shut down with "just reinvest lol".

**Comment by D3nnis3n** [comment]
Basically, you are completely right. The system isn't equitable at all and can and does cause unfair situations, this is resulting due to a game limitation though and hence only subsidiary within the scope of the constitution.

The problem is, though, that taxes like Income and Wealth tax are basic and important both for funding and guiding people, as well as in the sense of the RP concept. Prohibiting those taxes hence cannot be the solution, insofar the suggestion is 'impossible' to do.

If I had to weigh between the potential unfairness caused and the importance of such types of taxes, given we save tax debts and balances and the same issue actually happens in real life, just on a years scale, the weighting comes out in favour of keeping the taxes. If we didn't have that, it would likely be the other way around.

If there is any way to make the taxes itself more resistant to this problem without outright forbidding them, I'm very happy to hear about that. Similar to how Daniel was able to get EPs up to good standards. Unfortunately EPs have a much bigger effect on personal gameplay and the problem isn't remedied next day either, so while there the weighting goes out against the original versions of the EP law, the same cannot be true here.

**Comment by D3nnis3n** [comment]
Specifically that would mean:
How can those taxes be implemented in a way that is not sensitive to timing and still be equal to their real life counterparts, fulfilling all intended effects of them? (Including that you do not get money back if you have a positive tax balance, to avoid exploits and be true to a corporate tax, which our Income Tax actually is)

**Comment by thomasfn** [comment]
It depends what the goal of the income tax is. Many people say the purpose of it is to increase money velocity, which could be accomplished using a "stagnancy tax" - this tax would watch transactions in and out of the player's accounts and know how much money was untouched, and tax on that. This would also probably be a daily tick but the difference is the player has the whole 24 hr period to spend their money, and unexpected income or not whilst their offline right before the tick would not make any difference. I've also seen some ideas from FrostyLazer about a VAT that takes a different approach aswell.

IRL isn't really comparable because businesses have a "tick" of _an entire year_ to sort their balances, which is quite a bit different from WT's 24 hours - you don't really get situations where the business can't buy a bunch of stuff right before handing in their tax returns because their entire staff were asleep for 4 months straight.

At the very least the income tax could operate on a longer tick, e.g. 48 hrs, and that tick could be set at a "reasonable" time like evening CEST, and a song and dance made about it to give people plenty of time to deal with it. This wouldn't really fix the problem but offset much of the negative side effects. I've already explained to daniel how to make it tick when we want it and not on Eco's "whenever I feel like it" schedule.

In constitutional terms, I guess this would translate to a softer clause on timing sensitivity, e.g. "taxes which are sensitive to timing should make a reasonable effort to be equitable for people with varying play hours" or something, then let the judges decide if a tax oversteps those bounds or not.
